version: '3.8'

networks:
  gitea-net:
    driver: bridge

volumes:
  gitea-data:
  gitea-config:
  postgres-data:

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea_password
      POSTGRES_DB: gitea
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gitea-net

  gitea:
    image: gitea/gitea:latest
    restart: always
    environment:
      DB_TYPE: postgres
      DB_HOST: db:5432
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea_password
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
    depends_on:
      - db
    networks:
      - gitea-net
